"""Convert discovered Wowhead builds into the Lua data consumed by TalentFetch."""

from __future__ import annotations

import json
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "tools" / "wowhead_builds.json"
OUT = ROOT / "addon" / "TalentFetch_Data.lua"


def lua_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def main() -> None:
    data = json.loads(SOURCE.read_text(encoding="utf-8"))
    lines = [
        "-- Generated by tools/generate_build_data.py. Do not edit by hand.",
        "TalentFetchBuildData = {",
        f"    generatedAt = {int(data.get('generatedAt', time.time()))},",
        f"    source = {lua_string(data.get('source', 'wowhead'))},",
        "    builds = {",
    ]

    for build in data.get("builds", []):
        import_string = build.get("importString") or build.get("blizzardHash")
        if not import_string:
            continue
        lines.extend(
            [
                "        {",
                f"            name = {lua_string(str(build.get('name') or 'Wowhead Build'))},",
                f"            class = {lua_string(str(build.get('class') or ''))},",
                f"            spec = {lua_string(str(build.get('spec') or ''))},",
                f"            role = {lua_string(str(build.get('role') or ''))},",
                f"            content = {lua_string(str(build.get('content') or 'unknown'))},",
                f"            sourceUrl = {lua_string(str(build.get('sourceUrl') or ''))},",
                f"            importString = {lua_string(str(import_string))},",
                "        },",
            ]
        )

    lines.extend(["    },", "}", ""])
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    main()
